### ISSUE TITLE
App on shinyapps.io not responding

### ISSUE THREAD

**Issue by zsteinmetz** [wincowgerDEV/OpenSpecy#38]
For some reason, the current shinyapps.io instance at https://wincowger.shinyapps.io/OpenSpecy/ seems to be caught in a boot loop. I only see the white "please wait" screen and the page reloads every couple of seconds.

Might have something to do with #35 or #36.

**Comment by wincowgerDEV** [comment]
Hey Zacharias, 

Good catch. I see the boot loop on my end too. The thing is though, I haven't pushed any updates to https://wincowger.shinyapps.io/OpenSpecy/ since we started collaborating and it was working find yesterday. The logs also are not showing any issues. I think it is a shiny,io thing. The admin page is also running pretty slow. Going to look into it now.

**Comment by wincowgerDEV** [comment]
Weird, the new Open Specy website is working, but not the original one. I will first try pushing the original one again as it was when I last worked on it.

**Comment by wincowgerDEV** [comment]
Hmm, it is like there is a DOD attack or anything on it. I can see the logs have been normally active. I wonder if someone uploaded a code chunk and somehow that got read.

**Comment by wincowgerDEV** [comment]
Ended up being able to fix this using the restart button in shiny.io. It would be better to know why it happened, but for now, at least we can fix it if it happens again.
![image](https://user-images.githubusercontent.com/26821843/112317978-cdf87900-8c69-11eb-89d2-f6f41500020d.png)
